[tool.poetry]
name = "infrahub-demo-dc-fabric"
version = "0.1.0"
description = ""
authors = ["OpsMill <info@opsmill.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10, < 3.13"
infrahub-sdk = {version = "1.12.3", extras = ["all"]}
invoke = "^2.1.2"
# nornir-infrahub = "^0, >=0.2.2"
ansible-core = [
    { version = ">=2.15.9", python = ">=3.9,<3.10" },
    { version = ">=2.17.8", python = ">=3.10" },
]
netaddr = "^1.3.0"
paramiko = "^3.5.1"
deepmerge = "^2.0"
cvprac = "^1.3.1"
md-toc = "^9.0.0"
treelib = "^1.7.0"
jsonschema = "4.23"
# anta = "^0.11.0"
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
yamllint = "^1.35.1"
ruff = "^0.11.4"
mypy = "^1.14.1"
pytest = "^8.3.3"
infrahub-testcontainers = "1.2.12"
pytest-asyncio = "^0.26.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
filterwarnings = [
    "ignore:Module already imported so cannot be rewritten",
    "ignore:Deprecated call to",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
